services:
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - ${PWD}/data:/usr/src/app/data:delegated
      - ${PWD}/project:/usr/src/app/project:delegated
    environment:
      - USER_ID=1000
      - GROUP_ID=1000